project:
  type: website
  output-dir: docs

website:
  title: "Karolina Nugumanova"
  description: "Karolina Nugumanova: Personal Website"
  search: true
  navbar:
    # change color of navigation top panel, if you want
    #background: "#fefad4"
    #foreground: "black"
    logo: panda_flavicon.jpg
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd 
      #- teaching.qmd #if you want to use that pages uncomment them but you need to have relevant .qmd
      - academic_activities.qmd
      - CV.qmd

  favicon: panda_flavicon.jpg
  
  page-footer:
    # Change color of the bottom part of the site
    #background: "#464646"
    left: |
      <br>
      <br>
      {{< fa regular copyright >}} Karolina Nugumanova, 2023<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)<br>
      Opinions are my own and do not represent my employer
    
    right: |
      ![Logo image](logo_bottom.png){width=0px}<br> 
      <br>
      Made with [R-Studio](https://posit.co/download/rstudio-desktop/) and [Quarto](https://quarto.org/)<br>
      Inspiration and code snippets taken from [Emil Kamalov](https://emilkamalov.github.io/)
      
format:
  html:
    theme:
      #light: [Simplex]
      light: [Sandstone]
      #light: [Flatly]
      #light: [matria,styles.scss]
    css: styles.css
    toc: true
    
    # Additional things to control for all site
    #linkcolor: "#000000"
    #backgroundcolor: "#fcf9f2"
    #mainfont: "Roboto"
    fontsize: 13pt 
    

editor: visual

