project:
  type: website
  output-dir: docs

website:
  title: "Karolina Nugumanova" 
  description: "Karolina Nugumanova: Personal Website"
  google-analytics: "G-JSNW9RCCW1"
  search: true
  navbar:
    # change color of navigation top panel, if you want
    #background: "#cdc5c2"
    background: "#f5c37d"
    foreground: "#000000"
    logo: flavicon_new-removebg-preview.png
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - projects.qmd 
      #- teaching.qmd #if you want to use that pages uncomment them but you need to have relevant .qmd
      - academic_activities.qmd
      - CV.qmd

  favicon: main_flav_4.png
  
  page-footer:
    # Change color of the bottom part of the site
    #background: "#6aebc8"
    left: |
      <br>
      <br>
      <br>
      {{< fa regular copyright >}} Karolina Nugumanova, 2023<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)<br>
      Opinions are my own and do not represent my employer
    
    right: |
      ![Logo image](totoro-removebg-preview.png){width=100px}<br> 
      Made with [R-Studio](https://posit.co/download/rstudio-desktop/) and [Quarto](https://quarto.org/)<br>
      Inspiration and code snippets taken from [here](https://emilkamalov.github.io/)
      
format:
  html:
    theme:
      light: [Simplex]
      #light: [Sandstone]
      #light: [Flatly]
      #light: [matria,styles.scss]
    css: styles.css
    toc: true
    toc_float: 
     collapsed: true
     smooth_scroll: true
     toc_depth: 3
     number_sections: false
    
    # Additional things to control for all site
    linkcolor: "#000000"
    #backgroundcolor: "#ed961c"
    # mainfont: "Roboto"
    mainfont: "Academy Regular"
    # mainfont: "Quicksand Regular"
    fontsize: 13pt 
    

editor: visual

