---
title: "Academic Activities"
---

<!-- This css code to control size of the page title. Here it is 0 to make it invisible -->

```{=html}
<style>
.title {
  font-size: 0px;
}
</style>
```
### **Conferences and Expert Seminars**

**Russian Diaspora: trends, risks and entrepreneurship**. Kamalov E., Nugumanova K., Sergeeva I. Speakers: Nugumanova, Kamalov. *Russia Expert Seminar at EUI Robert Schuman centre "Russia's outlook in the new geopolitical reality"*. April 28, 2025. Villa Schifanoia, Via Boccaccio 121 - Florence.

**On the Move: Mobility, Integration, and Dynamics of Russian Emigration in 2022-2024**. Kamalov E., Nugumanova K., Sergeeva I. Speakers: Nugumanova, Kamalov. International business conference, *Kovcheg Business.Network*. April 23, 2025, zoom.

**On the Move: Mobility, Integration, and Dynamics of Russian Emigration in 2022-2024**. Kamalov E., Nugumanova K., Sergeeva I. Speakers: Nugumanova. International conference, *Academic Bridges*. March 8, 2025, zoom.

**Gendered Response to War: Analysing Patterns of Political Activism of Post-War Russian Emigrants, 2022-2023**.K. Nugumanova, E.Kamalov, I. Sergeeva. *ASEEES 2024 Annual Convention*. Nov. 21 – 24, 2024. Boston.

**Armenia in Focus: A Safer Haven for Russians.Hospitality, High Trust, and Low Repression**. New Russian Exodus and host societies: impacts and responses.*Yerevan University*. Nov. 14-15, 2024. Yerevan.

**Feminism in Action: Unveiling the Political Power of the Feminist Antiwar Resistance**. K.Nugumanova. *Aleksanteri Conference "Resisting Authoritarianism in Eurasia*". October 23-25, 2024. Helsinki.

[**Gendered Responses to War: Analyzing Differences and Underlying Factors in the Case of Russian Emigration, 2022-2023**](https://ethz.ch/content/dam/ethz/special-interest/gess/cis/cis-dam/CIS_2024/EGN24_Program.pdf). *15th European Graduate Network Conference*. April 3-5, 2024, Zurich.

<details>

<summary>Abstract</summary>

*Does gender influence responses to war, and if so, how? As Russia's invasion of Ukraine continues, the role of gender in political activism is becoming increasingly critical. While media coverage has highlighted feminist anti-war movements, scholarly research remains less comprehensive. Our study contributes to a broader understanding of gendered responses to war by focusing on a unique subpopulation: Russian wartime migrants. Unlike their counterparts who remain in Russia, these migrants often have the ability to voice opposition to the war abroad. We draw on data from the OutRush panel survey and qualitative interviews to explore the complexity of gender differences in political activism among these migrants. By combining threat theory, political opportunity structure, and the concept of «voice, exit, loyalty» we try to understand if and how there is a gender gap and how it manifests itself after emigration. Our initial findings reveal a reverse gender gap: Russian migrant women are more politically and civically engaged than men, despite facing greater economic and social challenges after emigration, as well as a poorer psycho-emotional state. This finding is surprising, given the patriarchal and authoritarian contexts in which Russian women are socialized. To identify the factors explaining this gender gap, we use regression modelling and the Blinder-Oaxaca decomposition method. Our analysis shows that conventional predictors, such as political interest and trust levels, are not significant. Moreover, variables related to the different migration struggles experienced by women and men contribute little to explaining the gap. Instead, feelings of responsibility and a desire for reparations for war victims largely account for this gap. Interviews with female activists further emphasize the critical role that war-related emotions play in decisions about political participation, civic engagement, and even the choice to emigrate*

</details>

**Cross-border voices: emigration, gender, and activism in the wake of the Russian invasion of Ukraine.** *Ilia State University, EDRAM Workshop*, Tbilisi, 18th-19th, April, 2024.

[**Two Years On: What’s Changed? Bright Prospects and Enduring Challenges for Russian Emigrants**](https://iaepan.edu.pl/wp-content/uploads/2024/03/In_Visible_program.pdf). *International Academic Conference (In)Visible Russian (Anti-)War Migration*, March 13-15, 2024, Warsaw.

<details>

<summary>Abstract</summary>

*The war in Ukraine has catalyzed a significant emigration wave from Russia, with approximately one million (Re:Russia, 28 July, 2023) individuals leaving mainly due to political dissent against Putin's regime. This study, utilizing data from three OutRush panel study, reveals these emigrants are predominantly younger, better educated, come from affluent backgrounds, and more politically active than the average Russian, with strong gender-egalitarian views and high trust in both compatriots and host nationals (Kamalov et al., March 2022). Their migration profoundly affects both origin and destination countries, influencing labor markets (Dustmann, Glitz, and Frattini, 2008), political landscapes (Kapur, 2014), and driving political changes in their countries of origin (Waldinger and Shams, 2023; Krawatzek and Müller-Funk, 2020; Barsbai et al., 2017). Their economic contributions and political activism potentially accelerate democratization processes (Escribà-Folch, Meseguer, and Wright, 2015; O'Mahony, 2013).Host societies stand to gain from these migrants' gender-equality perspectives and political engagement, which can enrich public discourse and hasten gender equality progress. However, their activism is declining due to increasing fear of (trans)national repression. Interestingly, the study revealed the phenomenon of a reverse gender gap in activism after emigration: women are more active in political life and civic engagement in the host countries compared to men.Regression analysis and the Blinder-Ooxaca decomposition method show that such a gap can be explained by the fact that women feel more responsible for Russia's actions in Ukraine and desire to compensate for the damage.In the two years since the beginning of the war, the psycho-emotional state of emigrants has changed. Сompared to September 2022, in the summer 2023 people show more optimism and less sadness, but trust in host institutions has decreased and worries about discrimination have increased. This article draws on quantitative data of three waves of panel survey OutRush and in-depth interviews with migrants and feminist anti-war activists to provide a comprehensive picture of the profile of Russian emigrants and the dynamics of their new post-war life*.

</details>

[**Gendered Responses to War: Analyzing Differences and Underlying Factors in the Case of Russian Emigration, 2022-2023**](https://lcsr.hse.ru/en/confsem/intersem/seminar2024/program/). *13th LCSR International Workshop “Recent Advances in Comparative Study of Values”*. Moscow, Myasnitskaya st. 11, and online. 23-26 April 2024.

**Gendered Response to War: Analysing Patterns of Political Activism of Post-War Russian Emigrants**. The 2023 Aleksanteri Conference [«Decolonizing Space in the Global East»](https://www.helsinki.fi/en/conferences/decolonizing-space-global-east/program). *University of Helsinki*, Finland, 23rd -25th of October, 2023.

<details>

<summary>Abstract</summary>

*In the wake of Russia's invasion of Ukraine, gender dynamics in political activism have come to the fore. While the media has reported extensively on the rise of a feminist anti-war resistance movement, the question remains whether there are indeed tangible gender differences in the political behaviour of post-war migrants and, if so, what factors underpin these differences. Although historical narratives depict politics as a predominantly male domain, with women traditionally showing lower levels of political engagement, recent shifts suggest a more complex landscape. Analyzing data from the OutRush panel survey, this study reveals that women, despite reporting heightened feelings of depression and a bleak outlook, consistently exhibit increased political and civic activism compared to men---except in assistance to fellow Russians. Intriguingly, conventional indicators, such as political interest and trust, displayed no gender disparity. A regression analysis posits that feelings of responsibility and the urge for reparations account for the observed gender gap, suggesting that these emotions might play a pivotal role in fueling women's political fervor. To refine our understanding of gendered motivations, a forthcoming Blinder-Oaxaca decomposition analysis will examine whether emotions such as responsibility and reparations drive political and civic engagement differently across genders. The quantitative data is complemented by extensive qualitative research, including interviews with numerous feminist anti-war resistance activists. These interviews explore their personal views on the contrasting experiences of male and female activists, and examines how gender norms and institutional frameworks in their host countries either support or hinder their activist endeavours. This research hopes to illuminate the intricate tapestry of gendered political activism in post-war migration scenarios.*

</details>

**Gender differences between post-war emigrants from Russia: guilt, sorrow, responsibility, and hope**. Co-authored with [Niсa Kostenko](https://il.linkedin.com/in/veronica-kostenko-b6bb6a26). The 2023 Aleksanteri Conference [«Decolonizing Space in the Global East»](https://www.helsinki.fi/en/conferences/decolonizing-space-global-east/program). *University of Helsinki*, Finland, 23rd -25th of October, 2023.

<details>

<summary>Abstract</summary>

*Using Outrush panel data collected from the initiative independent project we study how women and men who emigrated from Russia after 24.02.2022 differ in their attitudes. We specifically focus on their coping strategies, their modes of incorporation into receiving societies, their bonds with Russia, fears, and plans for the future. Women tend to feel more sorrow and pain, to miss their relatives and friends who stayed in Russia more than men, and are more often depressed and frustrated. Their political attitudes and political activities abroad also show diverse trends. Thus, women are more likely than men to take part in protests, sign petitions and post on social media. In addition, in both the first and second waves of the survey, women are more likely than men to volunteer, to help Ukrainian emigrants, and to donate to Russian and local NGOs. It is also noteworthy that women more actively try to integrate into the host community, learning local languages more readily than men. However, they were also more inclined to report experiencing discrimination from both locals in the host countries and local authorities. As we have 3 waves of data collected from the same people, we can trace the changes in various attitudes of women and men in emigration which allows for broader generalizations on the interaction of gender and migration status.*

</details>

[**War doesn't have a woman's face? Political behaviour and civic engagement of Russian post-war migrants: the gender dimension from the OutRush Longitudinal Study**](https://www.youtube.com/watch?v=1xf0jzZnG_U). International online conference ["In the footsteps of emigrants: in search of a new world"](http://www.academicbridges.sbs/?page_id=290&lang=ru) (Po sledam emigrantov: v poiskah novogo mira), *Academic Bridges*, *Kovcheg*, *Science at Risk*, in Russian, 23-25 June 2023).

**Gender Differences in Attitudes, Coping Strategies, and Integration among Russian Emigrants: A Longitudinal Study.** International Conference [«Problematizing Migration: Mobility and Vulnerablization in an Age of Abandonment and Inequalities»](https://www.fabula.org/actualites/115258/problematizing-migration-mobility-and-vulnerablization-in-an-age-of-abandonment-and-inequalities.html), *University of Palermo*, Italy, 17th -19th, July, 2023.

**The Objectivity of Popular Knowledge: A Social Semiotic Study of the Construction of Documentary Film Facts**. Annual English Language Student Conference. *European University at Saint Petersburg*, Russia, 2021.

**Cross-Border Repression and Solidarity: Navigating Threats, Discrimination, and Civic Engagement Among Russian Exiles**. E. Kamalov, I. Sergeeva, K.Nugumanova. Riga, 10-11 May, 2024

### **Workshops**

Gendered Responses to War: Analyzing Differences and Underlying Factors in the Case of Russian Emigration, 2022-2023. *Migration Working Group*, European University Institute, 15 February, 2024.

[Daily life in Venice: benefits and limits of high walkability. VIU Plenary Workshop "Venice. Talking to us"](https://www.univiu.org/images/aauniviu2017/GP/co-curr/VIU_WORKSHOP_ON_VENICE_S21_final_schedule.pdf). *Ca' Foscari University*, online, 2021.

Educational Sociology and Humanities Forum. St. Petersburg, Russia, 2021.

### **Professional trainings**

5-day training for interviewers under the auspices of the International Project Building the Anti-war Commons in the Russian Diaspora. Helsinki, Finland, 2022.

88-hour career track on Data Scientist with R. *DataCamp*, 2022.

Research, Ethics, Compliance, and Safety Training - CITI Program: Human Research. Social/Behavioral Researchers (2022); COVID-19: Public Training Series. Mental Health for Higher Ed and Healthcare (2022)

EY Business School: Introduction to auditing. Russia, 2019.

### **Summer Schools**

Experimental Designs in the Social and
Behavioral Sciences. Multifactorial Survey Experiments. *GESIS Spring Seminar 2025*, Unter Sachsenhausen 6-8, 50667 Cologne, Germany, March 31. − April 4, 2025

SPS Summer Academy 2022: (In)equality, Solidarity and Democracy in Europe. *European University Institute*, Italy, 2022.

Friedrich Naumann Foundation Online Summer School about war "Eclipse", 2022.

Data Science Summer School. *Hertie School Data Science Lab*, online, 2022.

### **Online courses**

Migration and Health: Enhancing Intercultural Competence and Diversity Sensitivity. *OpenWHO*, 2023.

Human Rights, Human Wrongs: Challenging Poverty, Vulnerability and Social Exclusion. *SDGAcademyX*, 2023.

Gender, Violence and Post-Conflict States. *University of Iceland*, 2022.

Qualitative research methods. *University of Amsterdam*, 2022.

Feminism and Social Justice. *University of California*, 2020.

Introduction to Tableau. *DataCamp*, 2022.
